base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	
	path('', views.home, name="home"),
	path('posts/', views.posts, name="posts"),
	path('post/<str:slug>', views.post, name="post"),
	path('profile/', views.profile, name="profile"),
	path('mail/', views.sendMail, name="mail"),
	path('mail_send/', views.mail, name="mail_send"),
	path('create_post/', views.createPost, name="create_post"),
	path('update_post/<str:slug>', views.updatePost, name="update_post"),
	path('delete_post/<str:slug>', views.deletePost, name="delete_post"),
	path('send_email/', views.send_email, name="send_email"),
	path('tag_post/<str:name>', views.tagPosts, name="tag_post")


]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Tag(models.Model):
	name = models.CharField(max_length = 200)
	thumbnail = models.ImageField(null = True, blank = True, upload_to = 'images', default = "desktop wallpaper.jpg")

	def __str__(self):
		return self.name
 
class Post(models.Model):
	headline = models.CharField(max_length = 200)
	sub_headline = models.CharField(max_length = 200)
	thumbnail = models.ImageField(null = True, blank = True, upload_to = 'images', default = "desktop wallpaper.jpg")
	body = RichTextUploadingField(null = True, blank = True)
	created = models.DateTimeField(auto_now_add = True)
	active = models.BooleanField(default = False)
	featured = models.BooleanField(default = False)
	tags = models.ManyToManyField(Tag, null = True)
	slug = models.SlugField(null = True, blank = True)

	def __str__(self):
		return self.headline

	def save(self, *args, **kwargs):

		if self.slug == None:
			slug = slugify(self.headline)

			has_slug = Post.objects.filter(slug = slug).exists()
			print(has_slug)
			count = 1
			while(has_slug):
				count += 1
				slug = slugify(self.headline) + '-' + str(count)
				has_slug = Post.objects.filter(slug = slug).exists()


			self.slug = slug

		super().save(*args, **kwargs)

class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete = models.CASCADE)
	user = models.CharField(max_length = 100, default = '')
	body = models.CharField(max_length = 1000)
	email = models.CharField(max_length = 100, default='')
	updated = models.DateTimeField(auto_now=True)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.id)

class SendMail(models.Model):
	email = models.CharField(max_length = 200)
	name = models.CharField(max_length = 100)

	def __str__(self):
		return self.name

base/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class CreatePost(ModelForm):
	class Meta:
		model = Post
		fields = '__all__'
		widgets = {
		'tags': forms.CheckboxSelectMultiple(),
		}

class CommentForm(ModelForm):
	body = forms.CharField(label='', 
                            widget=forms.Textarea(attrs={'placeholder': 'Add a comment...', 'cols':7, 'rows': 10}))
	user = forms.CharField(label='', 
                            widget=forms.TextInput(attrs={'placeholder': 'Enter Display Name:'}))
	email = forms.CharField(label='', 
                            widget=forms.TextInput(attrs={'placeholder': 'Enter Your Email:'}))
	class Meta:	
		model = Comment
		fields = ('user', 'body', 'email')

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import CreatePost, CommentForm
from .filters import PostFilter
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string

# Create your views here.

def home(request):
	posts = Post.objects.filter(active = True, featured = True)[0:3]
	tags = Tag.objects.all()[0:5]
	context = {'posts' : posts, 'tags':tags}	
	print(tags)
	return render(request, 'base/index.html', context)

def posts(request):
	posts = Post.objects.filter(active = True)
	myFilter = PostFilter(request.GET, queryset = posts)
	posts = myFilter.qs

	page = request.GET.get('page')
	paginator = Paginator(posts, 3)

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	print(posts.number)
	context = {'posts' : posts, 'myFilter' : myFilter}
	return render(request, 'base/posts.html', context)

def post(request, slug):
	post = Post.objects.get(slug = slug)
	c_form = CommentForm()
	if request.method == "POST":
		c_form = CommentForm(request.POST)
		if c_form.is_valid():
			instance = c_form.save(commit = False)
			instance.post = Post.objects.get(id = request.POST.get('post-id'))
			instance.user = request.POST.get('user')
			instance.email = request.POST.get('email')
			instance.save()
			c_form = CommentForm()

			email = EmailMessage(
				instance.user + ' Commented On ' + instance.post.headline,
				instance.body + ' Email: ' + instance.email,
				settings.EMAIL_HOST_USER,
				['tushar24081@gmail.com']
				)
			email.fail_silently = False
			email.send()
			print("Mail sent")
	context = {'posts' : post, 'c_form': c_form}
	return render(request, 'base/post.html', context)

def profile(request):
	return render(request, 'base/profile.html')

def tagPosts(request, name):
	posts = Post.objects.filter(tags__name = name)
	print(posts)
	myFilter = PostFilter(request.GET, queryset = posts)
	posts = myFilter.qs
	context = {'posts': posts, 'name':name}
	return render(request, 'base/posts.html', context)

@login_required(login_url = 'home')
def createPost(request):
	form = CreatePost()
	if request.method == "POST":
		form = CreatePost(request.POST, request.FILES)
		if form.is_valid():
			form.save()
		return redirect('posts')
	context = {'form' : form}
	return render(request, 'base/post_form.html', context)

@login_required(login_url = 'home')
def updatePost(request, slug):
	post = Post.objects.get(slug = slug)
	form = CreatePost(instance = post)
	if request.method == "POST":
		form = CreatePost(request.POST, request.FILES, instance = post)
		if form.is_valid():
			form.save()
		return redirect('posts')
	context = {'form' : form}
	return render(request, 'base/post_form.html', context)


@login_required(login_url = 'home')
def deletePost(request, slug):
	post = Post.objects.get(slug=slug)
	if request.method == 'POST':
		post.delete()
		return redirect('posts')
	context = {'item' : post}
	return render(request, 'base/delete_confirm.html', context)


def send_email(request):
	print("It's here..")
	if request.method == 'POST':
		template = render_to_string('base/email_template.html', {
			'name': request.POST['name'],
			'email': request.POST['email'],
			'message': request.POST['message'],
			})

		print(template)

		email = EmailMessage(
			request.POST['subject'],
			template,
			settings.EMAIL_HOST_USER,
			['tushar24081@gmail.com']
			)
		email.fail_silently = False
		email.send()

	return render(request, 'base/email_sent.html')
def sendMail(request):
	if request.method == "POST":
		email = request.POST.get('email')
		name = request.POST.get('name')

		if SendMail.objects.filter(email = email).exists():
			exist = True
		else:
			se = SendMail.objects.create(email = email, name=name)
			se.save()
			exist = False
		print("PROCESS DONE!!")
		print(exist)
		context = {
		'exist': exist
		}
	return render(request, 'base/mail.html', context)

def mail(request):
	if request.method == "POST":
		se = SendMail.objects.all()
		email_list = []

		for email in se:
			email_list.append(email.email)
		subject = request.POST.get('subject')
		html_content = request.POST.get('html_content')
		from_email = "tushar24081@gmail.com"
		text_content = ""
		to = email_list

		msg = EmailMultiAlternatives(subject, text_content, from_email, to)
		msg.attach_alternative(html_content, "text/html")
		msg.send()


	return render(request, 'base/sending_mail.html')

base/templates/base/delete_confirm.html
{% extends 'base/main.html' %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<form action="" method="POST">
	{% csrf_token %}
	<p>Are you sure you want to delete this {{item}} ? </p>
	<button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endblock content %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}
{% block content %}
<style type="text/css">

	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	.text-wrapper{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border: 1px solid #888;
		border-radius: 5px;
		padding: 14px;
	}
	.text-wrapper p{
		font-size: 14px;
	}

</style>
<div id="page-wrapper">
	<div class="text-wrapper content-block">
	<h2>Email has been sent</h2>
	<p>We'll try to reach to you in short time. Thank You!</p>
	<a href="{% url 'home' %}" class="btn btn-success">Back to home</a>
	</div>
</div>
{% endblock content %}

base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

base/templates/base/home.html
{% extends 'base/main.html' %}
{% block content %}
<h2>Home</h2>
{% endblock content %}

base/templates/base/mail.html
{% extends 'base/main.html' %}

{% block content %}
 <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

{% if exist %}
<div class="ui segment">
<div class="ui error message">
  <i class="close icon"></i>
  <div class="header">
    Maybe, you have already subscribed.
  </div>
  <ul class="list">
    <li>This email already exists at our Database.</li>
    <li>Please check it out again..</li>
  </ul>
</div>
</div>

{% else %}

<div class="ui segment">
  <div class="ui info message">
  <div class="header">
    Wohhoo, Thank You for subscribing the newsletter!
  </div>
  <ul class="list">
    <li>You'll get notified in your Inbox everytime I post something. </li>
    <li>You can Unsubscribe anytime.</li>
  </ul>
</div>
</div>

{% endif %}


{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>Tushar Rupani</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&family=Poppins:wght@300&family=Rubik&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/ir-black.min.css">

	<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"></script>
	<script>hljs.initHighlightingOnLoad()</script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">


    

    {% block title %}
	
	{% endblock title %}

 

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-digimedia-v1.css' %}">
    <link rel="stylesheet" href="{% static 'css/animated.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.css' %}">
	
</head>
<body>


	{% include 'base/navbar.html' %}

	{% block content %}

	{% endblock content %}

</body>
<script type="text/javascript">
		
		var static = "{% static 'css' %}"

	</script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	<!-- Scripts -->
  <script src="{% static 'js/owl-carousel.js' %} "></script>
  <script src="{% static 'js/animation.js' %}"></script>
  <script src="{% static 'js/imagesloaded.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</html>

base/templates/base/navbar.html
{% load static %}
<style type="text/css">
  .img{
    margin-left: -20px;
  }
</style>
			<header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="{% url 'home' %}" class="logo">
              <img src="{% static 'images/rupani.png'%}" alt="" class="img">
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
              <li class="scroll-to-section"><a href="{% url 'home' %}" class="active">Home</a></li>
              <li class="scroll-to-section"><a href="{% url 'home' %}#about">About</a></li>
              <li class="scroll-to-section"><a href="{% url 'home' %}#subscribe">Subscribe</a></li>
              <li class="scroll-to-section"><a href="{% url 'home' %}#portfolio">Projects</a></li>
              <li class="scroll-to-section"><a href="{% url 'home' %}#blog">Blog</a></li>
              <li class="scroll-to-section"><a href="{% url 'home' %}#contact">Contact</a></li> 

              {% if request.user.is_authenticated %}
              <li class="scroll-to-section"><div class="border-first-button"><a href="{% url 'posts' %}">Explore Blogs</a></div></li> 
              {% endif %}

            </ul>        
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>		

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
 <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<style type="text/css">
	
	body{
		background-color: #fff;
	}
	
	img{
		
		object-fit: cover;
		align-items: center;
		margin-top: 12px;
	}
	.center{
		max-width: 100%;
	}
	
	#id_body{

		margin: 10px;
	}
	#id_user{

		margin: 10px;
	}
	button{
		margin: 10px;
	}
	@media screen and (max-width:  1200px){
			.center{
			display: block;
			margin-left: auto;
			margin-right: auto;
			width: 70%;
		}
	}

	#id_body{
		width:  450px;
		height: 200px;
	}
	#id_user{
		width:  450px;
		height: 50px;
	}
	#id_email{
		width:  450px;
		height: 50px;
		margin-left: 10px;
	}
	.seg{
		width: 600px;
	}
	.f2{
		color: white;
	}
	
</style>

<br>
<br>
<br>
<br>
<br>


<img src="{{posts.thumbnail.url}}" class="center">

	<h1 style="margin-left: 18px">{{posts.headline}}</h1>

	

<h5 style="margin-left: 18px; margin-top: 20px">{{posts.sub_headline}}</h5>
<div class="body-wrapper">

<p style="margin-left: 30px; margin-top: 20px">{{posts.body|safe}}</p>


<form action="" method="POST" >
	{% csrf_token %}
	<input type="hidden" name="post-id" value="{{posts.id}}">
	<div class="ui inverted segment seg">
		<h2 class="f2">Please say something about this post</h2>
  <div class="ui inverted form">
  	{{c_form.user}}
  	<br>
  	{{c_form.email}}
  	<br>
    {{c_form.body}}
    <button type="submit" name="submit_c_form" class="btn btn-primary" style="margin-top: 12px; margin-bottom: 10px;">Send Comment</button>
  </div>
</div>
</form>


<h3>See what other people are telling about <b>{{posts.headline}}</b>:</h3>
	{% if posts.comment_set.all %}
			{% for c in posts.comment_set.all %}
			<div class="ui segment">
			<div class="ui comments">
  <div class="comment">
    <a class="avatar">
      <img src="{% static 'images/avtar.png' %}">
    </a>
    <div class="content">
      <a class="author">{{c.user}}</a>
      <div class="text">
        {{c.body}}
      </div>
      <div class="actions">
        <a class="reply">{{c.created|timesince}}</a>
        <a>
          <i class="expand icon"></i>
          Full-screen
        </a>
      </div>
    </div>
  </div>
</div>
</div>
			{% endfor %}
	{% else %}

	<div class="ui icon message">
  <i class="inbox icon"></i>
  <div class="content seg">
    <div class="header seg">
      No Comments till now..
    </div>
    <p>If this was helpful to you, please appreciate us!</p>
  </div>
</div>

	{% endif %}






{% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

<div class="main-container">
	<h3>Post Form</h3>
	<form action="" method="POST" enctype="multipart/form-data" class="ui form">
		
		{% csrf_token %}
		{{form.media}}
		{{form|crispy}}
		<br>
		<input type="submit" value="Submit" class="btn btn-primary">
	</form>
</div>
{% endblock content %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="main-container">
	<br>
	{% if myFilter == None %}
	{% else %}
	<form id="searchForm" action="" method="GET">
		{{myFilter.form|crispy}}
		<input type="submit" value="Submit" class="btn btn-primary">
		<br>
	</form>
	{% endif %}
	{% if name == None %}
		{% else %}
		<center><h1 style="margin-bottom:15px;">{{name}} Posts</h1></center>
		{% endif %}
	<div class="post-wrapper">

		{% for post in posts %}
				<div>
				<div class="post">
					<img class="thumbnail" src="{{post.thumbnail.url}}">
					<div class="post-preview">
						<h6 class="post-title">{{post.headline}}</h6>
						<p class="post-desc">{{post.sub_headline}}</p>
						<a href="{% url 'post' post.slug %}">Read More</a>
						{% if request.user.is_authenticated %}
							| <a href="{% url 'update_post' post.slug %}">Edit Post</a>
							| <a href="{% url 'delete_post' post.slug %}">Delete Post</a>
						{% endif %}
							<hr>
							
						{% for tag in post.tags.all %}
							<span class="tag">{{tag}}</span>
						{% endfor %}

					<hr>
					</div>
				
				</div>
			</div>
			{% empty %}

			<h2>Nothing Found </h2>
		{% endfor %}

				
			</div>
			
			<div class="row">
				<center>
			{% if posts.has_other_pages %}

			<ul class="pagination">
				{% if posts.has_previous %}
				<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">Previous</a></li>

				<li class="page-item"><a data-page="1" href="?page=1" class="page-link"> First</a></li>
				{% endif %}


				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
					{% endif %}
				{% endfor %}


				{% if posts.has_next %}
				<li class="page-item"><a data-page = "{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">Next</a></li>
				<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>
				{% endif %}
			</ul>

			{% endif %}
		</center>
			</div>


			

			</div>
<script type="text/javascript">
	
	let searchForm = document.getElementById("searchForm")
	let pageLinks = document.getElementsByClassName("page-link")

	for(var i = 0; pageLinks.length > i; i++){
		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault();
			let page = this.dataset.page
			console.log(page)
			searchForm.innerHTML += `<input value="${page}" name="page">`
			searchForm.submit()
		})
	}

</script>
{% endblock content %}

base/templates/base/profile.html
{% extends 'base/main.html' %}
{% block content %}
<h2>Profile</h2>
{% endblock content %}

base/templates/base/sending_mail.html
{% extends 'base/main.html' %}

{% block content %}
<link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<style type="text/css">
  .abc{
    padding: 5px 5px 5px 5px;
  }
</style>
<div class="ui segment abc">
      <form action="{% url 'mail_send' %}" method="post" class="ui form" enctype="multipart/form-data">
  {% csrf_token %}

  
     <div class="field">
      <label>Enter subject for emails:</label>
     <input type="text" placeholder="Ex: Regarding internship program..." name="subject">
   </div>
  


  
     <div class="field">
      <label>Enter HTML content for emails:</label>
      <textarea name="html_content" rows="10" cols="50"></textarea>
   </div>
  

  <button type="submit" class="ui primary button send-btn">Send Emails</button>

</form>
</div>


{% endblock content %}

base/templates/base/thanks.html
<h1>Thanks For Contacting</h1>